# Generated by Django 6.0.5 on 2026-05-12 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('audience', models.TextField()),
                ('tone', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('script', models.TextField(blank=True)),
                ('hook', models.TextField(blank=True)),
                ('hashtags', models.TextField(blank=True)),
                ('viral_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
