# Generated by Django 6.0.5 on 2026-05-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfbackend', '0003_alter_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail_titles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
