# Generated by Django 6.0.5 on 2026-05-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfbackend', '0004_project_thumbnail_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='alternative_hooks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
