# Generated by Django 6.0.5 on 2026-05-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfbackend', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail_images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
