# Generated by Django 6.0.5 on 2026-05-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfbackend', '0007_project_thumbnail_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
